// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKaqE7tyuo1aVeAII1sF46vtLe-QLmQGU',
    appId: '1:221144059340:web:333eb327ce44d943346169',
    messagingSenderId: '221144059340',
    projectId: 'flutter-app-productes-mpc',
    authDomain: 'flutter-app-productes-mpc.firebaseapp.com',
    databaseURL: 'https://flutter-app-productes-mpc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-mpc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSPs7IKRGSjlBlochjoeOpv-oDrr4YT4o',
    appId: '1:221144059340:android:b82c2ed8244399b9346169',
    messagingSenderId: '221144059340',
    projectId: 'flutter-app-productes-mpc',
    databaseURL: 'https://flutter-app-productes-mpc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-mpc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5Oqyt6oyxLquvxuh7C6iotODgyGOTdK0',
    appId: '1:221144059340:ios:5b7098841e2753cd346169',
    messagingSenderId: '221144059340',
    projectId: 'flutter-app-productes-mpc',
    databaseURL: 'https://flutter-app-productes-mpc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-mpc.firebasestorage.app',
    iosBundleId: 'com.example.productesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKaqE7tyuo1aVeAII1sF46vtLe-QLmQGU',
    appId: '1:221144059340:web:f26166804d0b2ec7346169',
    messagingSenderId: '221144059340',
    projectId: 'flutter-app-productes-mpc',
    authDomain: 'flutter-app-productes-mpc.firebaseapp.com',
    databaseURL: 'https://flutter-app-productes-mpc-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'flutter-app-productes-mpc.firebasestorage.app',
  );
}
